server {
    listen 80;
    root /var/www/public;
    index index.php index.html;

    location ~* \.(jpg|jpeg|png|gif|icon|svg|css|js|woff2|ttf|eot)$ {
        expires 1y;
        access_log off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass articles:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}